# -*- coding: utf-8 -*-
"""AreaePerimetroTriangulo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZLVmTJybYR2HkOCCHQIt8SilAf8Sd43q
"""

# Definindo as funções
print('Olá, seja bem-vindo(a)!\n')


p = int(input('O que deseja calcular o Triangulo? \n'
              '\n[1] - Perímetro'
              '\n[2] - Área \n'
              '\nEscolha:'))

if p == 1:

    lado1 = float(input('Digite o valor do lado1: '))
    lado2 = float(input('Digite o valor do lado2: '))
    lado3 = float(input('Digite o valor do lado3: '))

    perimetro = lado1 + lado2 + lado3
    print(f'O perímetro da figura é {perimetro}')

elif p == 2:

    altura = float(input('Altura: '))
    base =  float(input('Base: '))
    area = base * altura / 2
    print(f'A área da figura é {area}')

else:
    print('Opção inválida! Por favor, escolha 1 ou 2.')