# -*- coding: utf-8 -*-
"""CalcularAreaPerimetroQuadrilatero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dG0q9W1XzxPpIFjsPJ4MrBIEhXpSkcMd
"""

def calcular_area():
    print("\nEscolha a figura para calcular a área:")
    print("1 - Retângulo")
    print("2 - Quadrado")
    print("3 - Losango")
    print("4 - Trapézio")
    escolha = int(input("Escolha: "))

    if escolha == 1:
        b = float(input("Base: "))
        h = float(input("Altura: "))
        print(f"Área do Retângulo: {b * h}")
    elif escolha == 2:
        l = float(input("Lado: "))
        print(f"Área do Quadrado: {l ** 2}")
    elif escolha == 3:
        D = float(input("Diagonal maior: "))
        d = float(input("Diagonal menor: "))
        print(f"Área do Losango: {(D * d) / 2}")
    elif escolha == 4:
        B = float(input("Base maior: "))
        b = float(input("Base menor: "))
        h = float(input("Altura: "))
        print(f"Área do Trapézio: {((B + b) * h) / 2}")
    else:
        print("Opção inválida!")

def calcular_perimetro():
    print("\nEscolha a figura para calcular o perímetro:")
    print("1 - Retângulo")
    print("2 - Quadrado")
    print("3 - Losango")
    print("4 - Trapézio")
    escolha = int(input("Escolha: "))

    if escolha == 1:
        b = float(input("Base: "))
        h = float(input("Altura: "))
        print(f"Perímetro do Retângulo: {2 * (b + h)}")
    elif escolha == 2:
        l = float(input("Lado: "))
        print(f"Perímetro do Quadrado: {4 * l}")
    elif escolha == 3:
        l = float(input("Lado: "))
        print(f"Perímetro do Losango: {4 * l}")
    elif escolha == 4:
        B = float(input("Base maior: "))
        b = float(input("Base menor: "))
        L1 = float(input("Lado 1: "))
        L2 = float(input("Lado 2: "))
        print(f"Perímetro do Trapézio: {B + b + L1 + L2}")
    else:
        print("Opção inválida!")

while True:
    print("\nO que deseja calcular?")
    print("1 - Área")
    print("2 - Perímetro")
    print("3 - Sair")
    opcao = int(input("Escolha: "))

    if opcao == 1:
        calcular_area()
    elif opcao == 2:
        calcular_perimetro()
    elif opcao == 3:
        print("Saindo... Obrigado por usar o programa!")
        break
    else:
        print("Opção inválida! Tente novamente.")