# -*- coding: utf-8 -*-
"""Quadrilatero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J3hpahRSTjyw3AG3ENHmmjAHy4nwB_0k
"""

ado1 = float(input("Digite o comprimento do primeiro lado: "))
lado2 = float(input("Digite o comprimento do segundo lado: "))
lado3 = float(input("Digite o comprimento do terceiro lado: "))
lado4 = float(input("Digite o comprimento do quarto lado: "))

# Verifica se todos os lados são iguais
if lado1 == lado2 == lado3 == lado4:
    print("É um quadrado!")
else:
    print("Não é um quadrado.")

"""# Tarefa em Python

# Nova seção
"""